const GENERIC_BORDER = "#f1f1f1";
const GENERIC_BACKGROUND = "#fafafa";
const GREEN = "#66C2AE";
const YELLOW = "#F7E973";
const DISCORD_YELLOW = "#DD951F";
const DISCORD_RED = "#B04244";
const RED = "#EA415D";
const DISCORD_DARK = "#36393F";
const DISCORD_TEXT_ON_DARK = "#A5A7AB";
const DARK_ONE = "#292B3A";

export {
  GENERIC_BORDER,
  GENERIC_BACKGROUND,
  GREEN,
  YELLOW,
  RED,
  DARK_ONE,
  DISCORD_DARK,
  DISCORD_RED,
  DISCORD_TEXT_ON_DARK,
  DISCORD_YELLOW,
};
